### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by amarpotghan** [missingfaktor/dhall-scala#16]

**Comment by missingfaktor** [comment]
I did not notice that there was a default license in scaffold. Let's nuke that, and make sure that we use a license that abides by the license of Dhall itself.

**Comment by PanAeon** [comment]
@amarpotghan Could you, please,  commit the license? Not having a license prevents other people from forking this project.

**Comment by amarpotghan** [comment]
@PanAeon Sorry for this - I will do it asap.

**Comment by PanAeon** [comment]
Thank you!
