### ISSUE TITLE
Introduce scalafmt

### ISSUE THREAD

**Issue by missingfaktor** [missingfaktor/dhall-scala#17]
@amarpotghan I think your suggestion about scalafmt was right. It would be good to have a tool to enforce some of the style conventions we follow.

**Comment by chandan911** [comment]
Tried adding sbt plugins - scalafmt as well as scalariform as per their official docs. Both errored out in the dependency download stage itself.
It would seem we probably need to look for other proven library!

**Comment by missingfaktor** [comment]
@chandan911 Thanks for the update. Let's close this for now.

**Comment by chandan911** [comment]
@missingfaktor Yeah, we could do that. I'll keep looking for something meanwhile. Will open it if & when I find something worthwhile.
